### ISSUE TITLE
try! instead of ?

### ISSUE THREAD

**Issue by RCasatta** [TheBlueMatt/rust-lightning#1]
I see a lot of `try!` in the code, is there a reason to prefer it over `?`

**Comment by TheBlueMatt** [comment]
Not that I'm aware of? I just dove in and started writing stuff and didn't change when I discovered "?" existed :p.

**Comment by RCasatta** [comment]
submitted PR replacing try! with ? https://github.com/TheBlueMatt/rust-lightning/pull/3
